#!/sbin/openrc-run

depend() {
  need net
}

start() {
  ebegin "Starting ArangoDB"
  start-stop-daemon \
    --start \
    --exec /usr/sbin/arangod \
    --pidfile /var/run/arangod3.pid \
    --make-pidfile \
    --user arangodb3 \
    --background
  eend $? "Failed to start ArangoDB"
}

stop() {
  ebegin "Stopping ArangoDB"
  start-stop-daemon --stop --pidfile /var/run/arangod3.pid
  eend $? "Failed to stop ArangoDB"
}
